#Database credentials
postgres:
  uri: "postgres://user:1234@postgres:5432/hashdb?sslmode=disable"
  username: user
  password: 1234
  database_name: hashdb
#Server configurations
port: "9090"
logger:
  level: 5
  logfile: