version: '3.9'
services:
  web:
    build: .
    container_name: gowebapp
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "9090:9090"
    volumes:
      - ${VOLUME_PATH}:/local_path

  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: hashdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./postgres/input_data.sql:/docker-entrypoint-initdb.d/input_data.sql